### ISSUE TITLE
missing modules

### ISSUE THREAD

**Issue by superpitzi2** [maaaaz/thc-hydra-windows#14]
Hi

"Compiled with SSH and MySQL optional modules"
---------------------------------------
I have tried to use the http proxy module through burp but I cant, I tried all the possibilities and I get [ERROR] Unknown service: HYDRA_PROXY

For me I only need for http using burp testing.

Can you please compile with the http module, so we can use it through BURP or a way to configure the http or sock proxy please. I tried with proxifier and I cant manage to do it.
I even tried to compile entire cygwin and again I got errors. Maybe if you can try helping us ( as I have read a lot of comments and other people facing the same error trying to use hydra_proxy and couldnt do it.

Or if you dont wanna share, at least tell me what I did wrong hen compiling, when I use the .exe compiled i get an app crash.

Thank you.

**Comment by maaaaz** [comment]
Hello,

`http-proxy` **module** is not meant to define a proxy but to bruteforce a HTTP/socks proxy.

If you want to define a HTTP proxy in order to see/edit your request you have to set the environment variable first:
```
> set HYDRA_PROXY_HTTP=http://127.0.0.1:8080
> hydra -l admin -p admin <target> http-get
```
Please refer to **"Debugging Hydra with Burp Proxy"** on [this blog](https://blog.g0tmi1k.com/dvwa/bruteforce-low/) for further information.

Cheers.

**Comment by superpitzi2** [comment]
and in windows is not working, thats why I asked if possible to do that.

**Comment by maaaaz** [comment]
I forgot to say that I tested on Windows 7 with the latest `thc-hydra-windows` binaries and it worked.
